### ISSUE TITLE
Alpine

### ISSUE THREAD

**Issue by deini** [devalx/docker-teamspeak3#9]
Thoughts on porting to to Alpine base? :)

PD: Been using this image for almost 2 years and I absolutely love it <3

**Comment by devalx** [comment]
Actually i tried that several months (maybe even last year) ago, but i had trouble porting it to Alpine since Teamspeak itself is depending on standard glibc, and at that time it just didnt work out and the trouble seemed not worth it .. 
Maybe its more straightforward now, but currently i have no time to re-investigate.
But i see your point, Alpine as a base would be nice :-)

**Comment by BastiOfBerlin** [comment]
Have a look at [bastiofberlin/docker-teamspeak3](https://github.com/BastiOfBerlin/docker-teamspeak3).
